version: '3'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml

vars:
  APP_NAME: "dzh3159"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

  dmg:
    summary: Creates a DMG disk image for macOS distribution
    cmds:
      - task: darwin:dmg

  dmg:amd64:
    summary: Creates a DMG disk image for macOS amd64 distribution
    cmds:
      - task: darwin:dmg:amd64

  dmg:universal:
    summary: Creates a DMG disk image for macOS universal binary distribution
    cmds:
      - task: darwin:dmg:universal

